services:
  rest-api:
    container_name: rest-api
    image: todoapp/rest-api:0.0.2
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./firebase/service-account.json:/firebase/service-account.json
    environment:
      MONGODB_HOST: todoapp-mongodb
      GOOGLE_APPLICATION_CREDENTIALS: /firebase/service-account.json
    depends_on:
      - todoapp-mongodb

  todoapp-mongodb:
    image: mongo:7.0.1
    container_name: todoapp-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
