services:
  rest-api:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: todoapp-mongodb
    depends_on:
      - todoapp-mongodb

  todoapp-mongodb:
    image: mongo:7.0.1
    container_name: todoapp-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
